import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { Doctor, InsuranceDocumentation, Patient, PrescriptionItem, VisitSummary } from '../types';

const baseStyles = `
  <style>
    body { font-family: -apple-system, Helvetica, Arial, sans-serif; color: #0F172A; padding: 24px; }
    h1 { color: #0F766E; font-size: 20px; margin-bottom: 0; }
    .clinic { color: #64748B; font-size: 13px; margin-top: 2px; }
    .section { margin-top: 20px; }
    .label { color: #64748B; font-size: 11px; text-transform: uppercase; letter-spacing: 0.04em; }
    .value { font-size: 14px; margin-top: 2px; }
    table { width: 100%; border-collapse: collapse; margin-top: 12px; }
    th, td { text-align: left; padding: 8px; border-bottom: 1px solid #E2E8F0; font-size: 13px; }
    th { color: #64748B; font-weight: 600; }
    .footer { margin-top: 32px; color: #94A3B8; font-size: 11px; }
  </style>
`;

export async function generatePrescriptionPdf(
  patient: Patient,
  doctor: Doctor,
  diagnosis: string,
  items: PrescriptionItem[]
) {
  const rows = items
    .map(
      (item) => `
        <tr>
          <td>${item.drug}${item.brand ? ` (${item.brand})` : ''}</td>
          <td>${item.dose}</td>
          <td>${item.frequency}</td>
          <td>${item.duration}</td>
          <td>${item.instructions ?? ''}</td>
        </tr>`
    )
    .join('');

  const html = `
    <html>
      <head>${baseStyles}</head>
      <body>
        <h1>${doctor.name}</h1>
        <div class="clinic">${doctor.clinic} - ${doctor.specialty}</div>
        <div class="section">
          <div class="label">Patient</div>
          <div class="value">${patient.name}, ${patient.age} yrs, ${patient.gender}</div>
        </div>
        <div class="section">
          <div class="label">Diagnosis</div>
          <div class="value">${diagnosis || 'Not specified'}</div>
        </div>
        <div class="section">
          <div class="label">Prescription</div>
          <table>
            <tr><th>Medicine</th><th>Dose</th><th>Frequency</th><th>Duration</th><th>Instructions</th></tr>
            ${rows || '<tr><td colspan="5">No medicines added</td></tr>'}
          </table>
        </div>
        <div class="footer">Generated by AI Medical Scribe on ${new Date().toLocaleDateString()}. For clinician review before dispensing.</div>
      </body>
    </html>
  `;

  return printAndShare(html);
}

export async function generateVisitSummaryPdf(patient: Patient, doctor: Doctor, summary: VisitSummary) {
  const html = `
    <html>
      <head>${baseStyles}</head>
      <body>
        <h1>Visit Summary</h1>
        <div class="clinic">${doctor.clinic} - ${doctor.name}</div>
        <div class="section">
          <div class="label">Patient</div>
          <div class="value">${patient.name}, ${patient.age} yrs, ${patient.gender}</div>
        </div>
        <div class="section">
          <div class="label">Diagnosis</div>
          <div class="value">${summary.diagnosis}</div>
        </div>
        <div class="section">
          <div class="label">Medicines</div>
          <div class="value">${summary.medicines.replace(/\n/g, '<br/>')}</div>
        </div>
        <div class="section">
          <div class="label">Investigations</div>
          <div class="value">${summary.investigations}</div>
        </div>
        <div class="section">
          <div class="label">Follow-up</div>
          <div class="value">${summary.followUp}</div>
        </div>
        <div class="section">
          <div class="label">Lifestyle Advice</div>
          <div class="value">${summary.lifestyleAdvice}</div>
        </div>
        <div class="footer">Generated by AI Medical Scribe on ${new Date().toLocaleDateString()}.</div>
      </body>
    </html>
  `;

  return printAndShare(html);
}

export async function generateInsuranceDocumentationPdf(
  patient: Patient,
  doctor: Doctor,
  insurance: InsuranceDocumentation
) {
  const html = `
    <html>
      <head>${baseStyles}</head>
      <body>
        <h1>Insurance Claim Documentation</h1>
        <div class="clinic">${doctor.clinic} - ${doctor.name}</div>
        <div class="section">
          <div class="label">Patient</div>
          <div class="value">${patient.name}, ${patient.age} yrs, ${patient.gender}</div>
          <div class="value">Policy: ${patient.insurance}</div>
        </div>
        <div class="section">
          <div class="label">Diagnosis</div>
          <div class="value">${insurance.diagnosis}</div>
        </div>
        <div class="section">
          <div class="label">Procedures</div>
          <div class="value">${insurance.procedures}</div>
        </div>
        <div class="section">
          <div class="label">Clinical Justification</div>
          <div class="value">${insurance.clinicalJustification}</div>
        </div>
        <div class="section">
          <div class="label">Supporting Notes</div>
          <div class="value">${insurance.supportingNotes.replace(/\n/g, '<br/>')}</div>
        </div>
        <div class="footer">Generated by AI Medical Scribe on ${new Date().toLocaleDateString()}. For clinician review before submission.</div>
      </body>
    </html>
  `;

  return printAndShare(html);
}

async function printAndShare(html: string) {
  const { uri } = await Print.printToFileAsync({ html });
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri);
  }
  return uri;
}
