# Generated by Django 5.2.17 on 2026-09-13 16:24

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("tagline", models.CharField(max_length=160)),
                ("description", models.TextField()),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Package price in INR.",
                        max_digits=9,
                    ),
                ),
                ("duration_minutes", models.PositiveSmallIntegerField()),
                (
                    "icon",
                    models.CharField(
                        default="✦",
                        help_text="A single emoji or glyph for the card.",
                        max_length=8,
                    ),
                ),
                (
                    "requires_birth_details",
                    models.BooleanField(
                        default=True,
                        help_text="Chart-based services need date, time and place of birth.",
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("display_order", models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                "ordering": ("display_order", "name"),
            },
        ),
        migrations.CreateModel(
            name="Specialisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                ("slug", models.SlugField(max_length=60, unique=True)),
                ("description", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Astrologer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                (
                    "headline",
                    models.CharField(
                        help_text="One-line summary shown on listing cards.",
                        max_length=160,
                    ),
                ),
                ("bio", models.TextField()),
                (
                    "languages",
                    models.CharField(
                        help_text="Comma-separated, e.g. 'English, Hindi, Tamil'.",
                        max_length=160,
                    ),
                ),
                (
                    "years_experience",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(80)]
                    ),
                ),
                (
                    "rate_per_minute",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Indicative rate in INR per minute.",
                        max_digits=7,
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=5,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("consultations_done", models.PositiveIntegerField(default=0)),
                (
                    "photo_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional headshot. A monogram is shown when empty.",
                    ),
                ),
                ("is_accepting_bookings", models.BooleanField(default=True)),
                ("is_published", models.BooleanField(default=True)),
                (
                    "display_order",
                    models.PositiveSmallIntegerField(
                        default=100, help_text="Lower numbers are listed first."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "specialisations",
                    models.ManyToManyField(
                        related_name="astrologers", to="astrology.specialisation"
                    ),
                ),
            ],
            options={
                "ordering": ("display_order", "name"),
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=80)),
                ("location", models.CharField(blank=True, max_length=80)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("quote", models.TextField(max_length=600)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "astrologer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="testimonials",
                        to="astrology.astrologer",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="DailyHoroscope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sign",
                    models.CharField(
                        choices=[
                            ("aries", "Aries"),
                            ("taurus", "Taurus"),
                            ("gemini", "Gemini"),
                            ("cancer", "Cancer"),
                            ("leo", "Leo"),
                            ("virgo", "Virgo"),
                            ("libra", "Libra"),
                            ("scorpio", "Scorpio"),
                            ("sagittarius", "Sagittarius"),
                            ("capricorn", "Capricorn"),
                            ("aquarius", "Aquarius"),
                            ("pisces", "Pisces"),
                        ],
                        max_length=20,
                    ),
                ),
                ("day", models.DateField(default=datetime.date.today)),
                ("general", models.TextField()),
                ("love", models.CharField(max_length=300)),
                ("career", models.CharField(max_length=300)),
                ("health", models.CharField(max_length=300)),
                ("mood", models.CharField(max_length=40)),
                (
                    "lucky_number",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(99),
                        ]
                    ),
                ),
                ("lucky_colour", models.CharField(max_length=40)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="horoscopes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-day", "sign"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sign", "day"), name="unique_horoscope_per_sign_per_day"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(editable=False, max_length=12, unique=True),
                ),
                ("full_name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "birth_time",
                    models.TimeField(
                        blank=True,
                        help_text="As exact as known; affects the ascendant.",
                        null=True,
                    ),
                ),
                ("birth_place", models.CharField(blank=True, max_length=160)),
                ("preferred_datetime", models.DateTimeField()),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("call", "Phone call"),
                            ("video", "Video call"),
                            ("chat", "Chat"),
                        ],
                        default="call",
                        max_length=10,
                    ),
                ),
                ("question", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending review"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "astrologer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="astrology.astrologer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="astrology.service",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["status", "preferred_datetime"],
                        name="astrology_b_status_716d21_idx",
                    ),
                    models.Index(fields=["email"], name="astrology_b_email_86a3fe_idx"),
                ],
            },
        ),
    ]
