# Generated by Django 5.2.17 on 2026-10-03 15:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrology", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyhoroscope",
            name="day",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
